### ISSUE TITLE
Cannot construct tr.model.goals.data.Level

### ISSUE THREAD

**Issue by RadoslavCap** [thinkingrock-gtd/tr-pc#24]
When opening a data file with goals you'll get ObjectAccessException.

`Caused by: com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Cannot construct tr.model.goals.data.Level as it does not have a no-args constructor
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.newInstance(PureJavaReflectionProvider.java:71)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:428)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:233)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)`

Sample file with goals: [test1.zip](https://github.com/thinkingrock-gtd/tr-pc/files/10278557/test1.zip)

**Comment by RadoslavCap** [comment]
I've just found that the issue is on Linux (RHEL). By running application from source on Mac works well.
