### ISSUE TITLE
Report export in PDF format not working anymore

### ISSUE THREAD

**Issue by degrown** [thinkingrock-gtd/tr-pc#6]
As per @clairelema description:

> To reproduce, run a report, export as PDF. TR lets your save but in fact no file is saved.

**Comment by ursjoss** [comment]
I have been able to reproduce it with my data file. In my case it was an encoding problem. ThinkingRock writes a temporary xml file into the temp folder and passes it to JasperReports. Apparently it doesn't properly encoding utf-8 content, which leads to a `SAXParseException`.

<details><summary>Stacktrace</summary>
<pre>
[Fatal Error] Actions.xml:3602:147: Zeichenreferenz "&#55357" ist ein ungültiges XML-Zeichen.
net.sf.jasperreports.engine.JRException: Failed to parse the xml document
	at net.sf.jasperreports.engine.util.JRXmlUtils.parse(JRXmlUtils.java:125)
	at net.sf.jasperreports.engine.data.JRXmlDataSource.<init>(JRXmlDataSource.java:378)
	at net.sf.jasperreports.engine.data.JRXmlDataSource.<init>(JRXmlDataSource.java:391)
	at net.sf.jasperreports.engine.data.JRXmlDataSource.<init>(JRXmlDataSource.java:386)
	at au.com.trgtd.tr.reports.actions.doasap.ReportImpl.process(ReportImpl.java:137)
	at au.com.trgtd.tr.reports.actions.doasap.ReportActionImpl.performAction(ReportActionImpl.java:39)
	at org.openide.util.actions.CallableSystemAction$1.run(CallableSystemAction.java:105)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:70)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:91)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:74)
	at org.openide.util.actions.CallableSystemAction.actionPerformed(CallableSystemAction.java:102)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.xml.sax.SAXParseException; systemId: file:/tmp/Actions.xml; lineNumber: 3602; columnNumber: 147; Zeichenreferenz "&#55357" ist ein ungültiges XML-Zeichen.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
	at net.sf.jasperreports.engine.util.JRXmlUtils.parse(JRXmlUtils.java:121)
	... 48 more
</pre>
</details>

**Comment by ursjoss** [comment]
I have a quick-and-dirty working solution, but need a moment to get organized in the otherwise still quite unknown codebase. I will provide a PR in the next days.

**Comment by degrown** [comment]
Thanks @ursjoss 
I'll be glad to help you testing it but I think I'm not able to "build" a TR working instance.
@jeremy-moore  once wrote "I will look into first build instructions", but I don't know if it's really already clear for you.

**Comment by ursjoss** [comment]
Thanks @degrown, testing and reviewing will be necessary before merge.

As for the build instructions: @jeremy-moore's instructions will be very helpful. I'm lookig forward to seeing them.

In the mean-time: I played around a bit with the project and figured out two ways how to build and use the tool from sources (using ant and directly from Netbeans). But as I had no previous (real) experience with either ant or Netbeans, it may not be the canonical way. I'll document my steps on the way with the PR and we can share and improve that.
