### ISSUE TITLE
IndexOutOfBoundsException: Invalid range

### ISSUE THREAD

**Issue by ursjoss** [thinkingrock-gtd/tr-pc#9]
When launching TrhinkingRock from current main, switching between different action tabls may fail with an `IndexOutOfBoundsException: Invalid Range`. From a user perspective, the newly selected tab will be empty. In many cases, selecting another tab and re-selecting the one that initially failed will result in a tab that properly shows the tasks from that tab.

In fact toggling between two different tabs may alternate between tasks shown and now shown (with the error thrown).

<details><summary>Sample Stacktrace</summary>
<pre>
WARNING [org.openide.windows.WindowManager]: [Winsys] TopComponent au.com.trgtd.tr.view.actns.screens.ReviewActionsTopComponent throws runtime exception from its componentShowing() method.
Please repair it!
java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsDeleted(DefaultRowSorter.java:891)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsDeleted(DefaultSortController.java:398)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4279)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4123)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at ca.odell.glazedlists.swing.EventTableModel.listChanged(EventTableModel.java:211)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter$ListEventFormat.fire(ListEventAssembler.java:781)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter$ListEventFormat.fire(ListEventAssembler.java:773)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:445)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:344)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter.fireEvent(ListEventAssembler.java:767)
	at ca.odell.glazedlists.event.ListEventAssembler$AssemblerHelper.commitEvent(ListEventAssembler.java:416)
	at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:249)
	at ca.odell.glazedlists.BasicEventList.clear(BasicEventList.java:193)
	at au.com.trgtd.tr.view.actns.screens.ReviewActionsPanel.resetModel(ReviewActionsPanel.java:555)
	at au.com.trgtd.tr.view.actns.screens.ReviewActionsTopComponent.componentShowing(ReviewActionsTopComponent.java:223)
[catch] at org.openide.windows.WindowManager.componentShowing(WindowManager.java:314)
	at org.netbeans.core.windows.WindowManagerImpl.componentShowing(WindowManagerImpl.java:1226)
	at org.netbeans.core.windows.view.DefaultView.changeGUI(DefaultView.java:143)
	at org.netbeans.core.windows.ViewRequestor.dispatchRequest(ViewRequestor.java:250)
	at org.netbeans.core.windows.ViewRequestor.processRequest(ViewRequestor.java:226)
	at org.netbeans.core.windows.ViewRequestor.postRequest(ViewRequestor.java:164)
	at org.netbeans.core.windows.ViewRequestor.scheduleRequest(ViewRequestor.java:102)
	at org.netbeans.core.windows.Central.addModeOpenedTopComponent(Central.java:766)
	at org.netbeans.core.windows.ModeImpl.addOpenedTopComponent(ModeImpl.java:333)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpenAtTabPosition(WindowManagerImpl.java:1295)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpen(WindowManagerImpl.java:1252)
	at org.openide.windows.TopComponent.open(TopComponent.java:472)
	at org.openide.windows.TopComponent.open(TopComponent.java:452)
	at au.com.trgtd.tr.view.actns.RAAction$2.run(RAAction.java:128)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>
</details>

## How to reproduce

- Open ThinkingRock from main (without the code changes from this PR).
- Make sure to open a data file with multiple tasks and ensure you have more than one action tab
- Open the actions view and jump between different tabs. To observe the problem 
  - look for the exception in the logs or in system out
  - see that the actions are not always listed in the different action tabs.
- Open Thinking rock from the associated PR and do the same steps to see that
  - there is no such error in the logs/system out and
  - jumping between action tabs will always show the actions as expected.

**Comment by degrown** [comment]
Hi @ursjoss, I think I've seen blank tabs in the past too!
As I wrote [here](https://github.com/thinkingrock-gtd/tr-discuss-governance/discussions/11#discussioncomment-1801704), I'm currently stuck in a corner: using a jdk version not already supported on development branch...so I can't test this, but I fully trust you.
Let me know if I can help in any way.
